In [1]:
import pandas as pd
import json
from pandas.io.json import json_normalize

In [2]:
data = []
path = './yelp_dataset/yelp_academic_dataset_business.json'
with open(path,'r',encoding='UTF-8') as f:
    for line in f:
        data.append(json.loads(line))
        
df = json_normalize(data)

In [4]:
df.columns

Index(['address', 'attributes', 'attributes.AcceptsInsurance',
       'attributes.AgesAllowed', 'attributes.Alcohol', 'attributes.Ambience',
       'attributes.BYOB', 'attributes.BYOBCorkage', 'attributes.BestNights',
       'attributes.BikeParking', 'attributes.BusinessAcceptsBitcoin',
       'attributes.BusinessAcceptsCreditCards', 'attributes.BusinessParking',
       'attributes.ByAppointmentOnly', 'attributes.Caters',
       'attributes.CoatCheck', 'attributes.Corkage',
       'attributes.DietaryRestrictions', 'attributes.DogsAllowed',
       'attributes.DriveThru', 'attributes.GoodForDancing',
       'attributes.GoodForKids', 'attributes.GoodForMeal',
       'attributes.HairSpecializesIn', 'attributes.HappyHour',
       'attributes.HasTV', 'attributes.Music', 'attributes.NoiseLevel',
       'attributes.Open24Hours', 'attributes.OutdoorSeating',
       'attributes.RestaurantsAttire', 'attributes.RestaurantsCounterService',
       'attributes.RestaurantsDelivery', 'attributes.RestaurantsGoodForGroups',
       'attributes.RestaurantsPriceRange2',
       'attributes.RestaurantsReservations',
       'attributes.RestaurantsTableService', 'attributes.RestaurantsTakeOut',
       'attributes.Smoking', 'attributes.WheelchairAccessible',
       'attributes.WiFi', 'business_id', 'categories', 'city', 'hours',
       'hours.Friday', 'hours.Monday', 'hours.Saturday', 'hours.Sunday',
       'hours.Thursday', 'hours.Tuesday', 'hours.Wednesday', 'is_open',
       'latitude', 'longitude', 'name', 'neighborhood', 'postal_code',
       'review_count', 'stars', 'state'],
      dtype='object')

In [17]:
postal_codes = df.postal_code.unique()

In [67]:
df.groupby(['state','city']).count()

                               address  attributes  \
state city
01    Moss                          11           0
10    Ferrel                         1           0
11    Montr√©al De L'aube             1           0
4     Enns                           1           0
45    Parma                          1           0
6     Haus                           3           0
AB    Airdrie                      168           0
      Alberta Park Industrial        1           0
      Balzac                        12           0
      Beltline                       1           0
      Bro                            1           0
      CALGARY                        2           0
      Calgary                     7383           0
      Chestermere                   34           0
      Division No. 6                 4           0
      Downtown                       2           0
      East Calgary                   1           0
      Edgemont                       1           0
      Edgewater                      1           0
      Highland Park                  1           0
      Indus                          1           0
      Midnapore                      1           0
      Montreal                       1           0
      North York                     1           0
      NorthEast Calgary              1           0
      NorthWest Calgary              3           0
      Northeast Calgary              1           0
      Northwest Calgary              3           0
      Richmond                       1           0
      Rocky View                    18           0
...                                ...         ...
WI    Brooklyn                       5           0
      Cottage Grove                 38           0
      Cross Plains                  23           0
      Dane                           6           0
      De Forest                     27           0
      DeForest                      28           0
      Fitchburg                    199           0
      Fitchburgh                     1           0
      Hawthorne                      1           0
      MADISON                        1           0
      Madison                     3415           0
      Mc Farland                    31           0
      McFarland                     30           0
      Midddleton                     1           0
      Middleton                    347           0
      Monona                       135           0
      Mount Horeb                   55           0
      Mt. Horeb                      1           0
      Oregon                        72           0
      Paoli                          3           0
      Shorewood Hills                2           0
      Springfield                    1           0
      Stoughton                    109           0
      Sun Prairie                  244           0
      Verona                       137           0
      Vilas                          1           0
      Waunakee                      85           0
      Windsor                       15           0
XGM   Trafford                      23           0
XMS   Queens Square                  1           0

                               attributes.AcceptsInsurance  \
state city
01    Moss                                               0
10    Ferrel                                             0
11    Montr√©al De L'aube                                 0
4     Enns                                               0
45    Parma                                              0
6     Haus                                               0
AB    Airdrie                                            5
      Alberta Park Industrial                            0
      Balzac                                             0
      Beltline                                           0
      Bro                                                0
      CALGARY                                            0
      Calgary                                          242
      Chestermere                                        2
      Division No. 6                                     0
      Downtown                                           0
      East Calgary                                       0
      Edgemont                                           0
      Edgewater                                          0
      Highland Park                                      0
      Indus                                              0
      Midnapore                                          0
      Montreal                                           0
      North York                                         0
      NorthEast Calgary                                  0
      NorthWest Calgary                                  0
      Northeast Calgary                                  0
      Northwest Calgary                                  0
      Richmond                                           0
      Rocky View                                         0
...                                                    ...
WI    Brooklyn                                           0
      Cottage Grove                                      2
      Cross Plains                                       1
      Dane                                               0
      De Forest                                          0
      DeForest                                           1
      Fitchburg                                         11
      Fitchburgh                                         0
      Hawthorne                                          0
      MADISON                                            0
      Madison                                          147
      Mc Farland                                         0
      McFarland                                          1
      Midddleton                                         0
      Middleton                                         17
      Monona                                             5
      Mount Horeb                                        1
      Mt. Horeb                                          0
      Oregon                                             0
      Paoli                                              0
      Shorewood Hills                                    0
      Springfield                                        0
      Stoughton                                          1
      Sun Prairie                                       11
      Verona                                             5
      Vilas                                              0
      Waunakee                                           4
      Windsor                                            0
XGM   Trafford                                           0
XMS   Queens Square                                      0

                               attributes.AgesAllowed  attributes.Alcohol  \
state city
01    Moss                                          0                   8
10    Ferrel                                        0                   0
11    Montr√©al De L'aube                            0                   0
4     Enns                                          0                   0
45    Parma                                         0                   1
6     Haus                                          0                   0
AB    Airdrie                                       0                  43
      Alberta Park Industrial                       0                   0
      Balzac                                        0                   3
      Beltline                                      0                   0
      Bro                                           0                   0
      CALGARY                                       0                   0
      Calgary                                      13                2174
      Chestermere                                   0                   6
      Division No. 6                                0                   1
      Downtown                                      0                   0
      East Calgary                                  0                   0
      Edgemont                                      0                   0
      Edgewater                                     0                   0
      Highland Park                                 0                   0
      Indus                                         0                   0
      Midnapore                                     0                   1
      Montreal                                      0                   0
      North York                                    0                   0
      NorthEast Calgary                             0                   0
      NorthWest Calgary                             0                   0
      Northeast Calgary                             0                   0
      Northwest Calgary                             0                   1
      Richmond                                      0                   0
      Rocky View                                    0                   7
...                                               ...                 ...
WI    Brooklyn                                      0                   2
      Cottage Grove                                 0                   9
      Cross Plains                                  0                  11
      Dane                                          0                   2
      De Forest                                     0                   8
      DeForest                                      0                   7
      Fitchburg                                     0                  55
      Fitchburgh                                    0                   0
      Hawthorne                                     0                   1
      MADISON                                       0                   0
      Madison                                       7                 975
      Mc Farland                                    0                   6
      McFarland                                     0                  10
      Midddleton                                    0                   0
      Middleton                                     1                 105
      Monona                                        0                  41
      Mount Horeb                                   0                  18
      Mt. Horeb                                     0                   0
      Oregon                                        0                  22
      Paoli                                         0                   2
      Shorewood Hills                               0                   1
      Springfield                                   0                   1
      Stoughton                                     0                  30
      Sun Prairie                                   0                  64
      Verona                                        0                  31
      Vilas                                         0                   0
      Waunakee                                      0                  22
      Windsor                                       0                   3
XGM   Trafford                                      0                   8
XMS   Queens Square                                 0                   0

                               attributes.Ambience  attributes.BYOB  \
state city
01    Moss                                       8                0
10    Ferrel                                     0                0
11    Montr√©al De L'aube                         0                0
4     Enns                                       0                0
45    Parma                                      1                0
6     Haus                                       0                0
AB    Airdrie                                   50                0
      Alberta Park Industrial                    0                0
      Balzac                                     0                0
      Beltline                                   0                0
      Bro                                        0                0
      CALGARY                                    0                0
      Calgary                                 2155                0
      Chestermere                                9                0
      Division No. 6                             1                0
      Downtown                                   0                0
      East Calgary                               0                0
      Edgemont                                   0                0
      Edgewater                                  1                0
      Highland Park                              0                0
      Indus                                      0                0
      Midnapore                                  1                0
      Montreal                                   0                0
      North York                                 0                0
      NorthEast Calgary                          0                0
      NorthWest Calgary                          0                0
      Northeast Calgary                          0                0
      Northwest Calgary                          1                0
      Richmond                                   0                0
      Rocky View                                 7                0
...                                            ...              ...
WI    Brooklyn                                   2                0
      Cottage Grove                             11                0
      Cross Plains                              10                0
      Dane                                       3                0
      De Forest                                  8                0
      DeForest                                   9                0
      Fitchburg                                 55                2
      Fitchburgh                                 0                0
      Hawthorne                                  1                0
      MADISON                                    0                0
      Madison                                  920               50
      Mc Farland                                 6                0
      McFarland                                  9                0
      Midddleton                                 0                0
      Middleton                                 97                2
      Monona                                    45                0
      Mount Horeb                               15                0
      Mt. Horeb                                  0                0
      Oregon                                    19                0
      Paoli                                      2                0
      Shorewood Hills                            1                0
      Springfield                                0                0
      Stoughton                                 31                0
      Sun Prairie                               64                0
      Verona                                    36                0
      Vilas                                      0                0
      Waunakee                                  23                0
      Windsor                                    4                0
XGM   Trafford                                   5                0
XMS   Queens Square                              0                0

                               attributes.BYOBCorkage  attributes.BestNights  \
state city
01    Moss                                          0                      0
10    Ferrel                                        0                      0
11    Montr√©al De L'aube                            0                      0
4     Enns                                          0                      0
45    Parma                                         0                      0
6     Haus                                          0                      0
AB    Airdrie                                       0                      5
      Alberta Park Industrial                       0                      0
      Balzac                                        0                      0
      Beltline                                      0                      0
      Bro                                           0                      0
      CALGARY                                       0                      0
      Calgary                                       0                    279
      Chestermere                                   0                      1
      Division No. 6                                0                      0
      Downtown                                      0                      0
      East Calgary                                  0                      0
      Edgemont                                      0                      0
      Edgewater                                     0                      0
      Highland Park                                 0                      0
      Indus                                         0                      0
      Midnapore                                     0                      0
      Montreal                                      0                      0
      North York                                    0                      0
      NorthEast Calgary                             0                      0
      NorthWest Calgary                             0                      0
      Northeast Calgary                             0                      0
      Northwest Calgary                             0                      0
      Richmond                                      0                      0
      Rocky View                                    0                      1
...                                               ...                    ...
WI    Brooklyn                                      0                      0
      Cottage Grove                                 0                      1
      Cross Plains                                  0                      1
      Dane                                          0                      1
      De Forest                                     0                      0
      DeForest                                      0                      1
      Fitchburg                                     2                      9
      Fitchburgh                                    0                      0
      Hawthorne                                     0                      0
      MADISON                                       0                      0
      Madison                                      65                    192
      Mc Farland                                    0                      2
      McFarland                                     0                      2
      Midddleton                                    0                      0
      Middleton                                     2                     20
      Monona                                        0                      3
      Mount Horeb                                   0                      1
      Mt. Horeb                                     0                      0
      Oregon                                        0                      4
      Paoli                                         0                      0
      Shorewood Hills                               0                      0
      Springfield                                   0                      0
      Stoughton                                     0                      2

In [8]:
mf = pd.read_csv('DOHMH_New_York_City_Restaurant_Inspection_Results.csv')

In [30]:
zipcodes = mf.ZIPCODE.fillna(0).unique().astype(object)

In [31]:
def Intersection(lst1, lst2): 
    return set(lst1).intersection(lst2)

In [33]:
zipcodes

array([11249.0, 10012.0, 10003.0, 10282.0, 10036.0, 11421.0, 10024.0,
       11418.0, 11368.0, 10014.0, 11203.0, 11216.0, 11201.0, 11237.0,
       10025.0, 10019.0, 10462.0, 11372.0, 11222.0, 10005.0, 11232.0,
       10463.0, 11373.0, 10007.0, 11101.0, 11233.0, 10010.0, 11226.0,
       10002.0, 10017.0, 11103.0, 11234.0, 11004.0, 11210.0, 10018.0,
       11236.0, 10030.0, 10128.0, 10301.0, 10001.0, 10451.0, 11354.0,
       10009.0, 11358.0, 11238.0, 10469.0, 11426.0, 10038.0, 10033.0,
       10028.0, 11207.0, 11411.0, 11215.0, 11220.0, 10455.0, 11225.0,
       10457.0, 11432.0, 10065.0, 11224.0, 10026.0, 11415.0, 11205.0,
       10006.0, 11228.0, 10029.0, 0.0, 10013.0, 10016.0, 11211.0, 10075.0,
       11209.0, 11374.0, 11355.0, 11385.0, 11435.0, 11214.0, 11208.0,
       10031.0, 11428.0, 11360.0, 10021.0, 10011.0, 11366.0, 11357.0,
       10470.0, 10035.0, 10032.0, 10314.0, 11104.0, 11106.0, 11375.0,
       10027.0, 10465.0, 11430.0, 10308.0, 10306.0, 10305.0, 10456.0,
       11414.0, 10112.0, 10023.0, 10022.0, 10310.0, 10302.0, 11223.0,
       11361.0, 11204.0, 11427.0, 11231.0, 11369.0, 11423.0, 10461.0,
       11434.0, 10312.0, 11364.0, 11419.0, 11218.0, 11422.0, 10110.0,
       10468.0, 11420.0, 11206.0, 11433.0, 11217.0, 11378.0, 10458.0,
       11377.0, 10304.0, 10467.0, 11102.0, 10454.0, 10004.0, 10040.0,
       10452.0, 10459.0, 11229.0, 10121.0, 10464.0, 10472.0, 11235.0,
       10309.0, 10453.0, 11230.0, 11365.0, 11362.0, 10474.0, 11212.0,
       11694.0, 11219.0, 10466.0, 11105.0, 11213.0, 10039.0, 11367.0,
       10169.0, 10034.0, 11412.0, 11356.0, 11417.0, 11693.0, 11239.0,
       11040.0, 11413.0, 11429.0, 11436.0, 10280.0, 11416.0, 10118.0,
       11379.0, 10460.0, 11221.0, 10307.0, 10471.0, 10473.0, 10103.0,
       10475.0, 10303.0, 11692.0, 11109.0, 11691.0, 11370.0, 10037.0,
       10179.0, 10119.0, 10041.0, 10044.0, 10281.0, 10177.0, 10111.0,
       10170.0, 10020.0, 10048.0, 10069.0, 10279.0, 10105.0, 10000.0,
       11005.0, 10153.0, 11697.0, 10178.0, 11363.0, 10158.0, 10167.0,
       10154.0, 10115.0, 10107.0, 10168.0, 10173.0, 10176.0, 11001.0,
       10106.0, 10174.0, 11242.0, 10271.0, 10171.0, 11371.0, 10165.0,
       10123.0, 10172.0, 10055.0, 11241.0, 10080.0, 10155.0], dtype=object)

In [37]:
for i in postal_codes:
    if i.startswith('11') or i.startswith('10'):
        print(i)

10300
101 23
11290

In [40]:
for i in zipcodes:
    if int(i) == 10123:
        print(i)

10123.0

In [41]:
sf = pd.read_csv('sf_data.csv')

In [42]:
sf.columns

Index(['business_id', 'business_name', 'business_address', 'business_city',
       'business_state', 'business_postal_code', 'business_latitude',
       'business_longitude', 'business_location', 'business_phone_number',
       'inspection_id', 'inspection_date', 'inspection_score',
       'inspection_type', 'violation_id', 'violation_description',
       'risk_category'],
      dtype='object')

In [44]:
sf_zipcodes = sf.business_postal_code.fillna(0).astype(object).unique()

In [45]:
sf_zipcodes

array(['94118', '94124', '94109', '94102', '94110', '94103', '94108',
       '94122', 0, '94107', '94114', '94134', '94121', '94111', '94123',
       '94133', '94117', '94112', '94105', '94115', '94143', '94132',
       '94104', '94127', '94131', '94130', '94116', '94120', '94158',
       '94602', '95133', '95132', '941102019', '94301', '94013', '94901',
       '941033148', '94101', '94402', '94621', '95105', '94544', 'Ca',
       'CA', '941', '94129', '95109', '64110', '95117', '94080', '94188',
       '92672', '00000', '95122', '94014'], dtype=object)

In [71]:
for i in postal_codes:
    if i.startswith('89'):
        print(i)

89002
89106
89031
89128
89102
89109
89131
89149
89141
89011
89146
89130
89012
89030
89135
89110
89169
89121
89120
89086
89118
89148
89119
89113
89117
89129
89123
89183
89032
89147
89122
89134
89044
89104
89158
89052
89014
89101
89103
89138
89107
89074
89139
89108
89142
89178
89005
89166
89156
89115
89081
89133
89015
89084
89184
89145
89143
89136
89013
89191
89151
89180
89144
89085
89053
89114
8967
89199
89137
89009
89154
89054
89434
89077
89111
89003
89006
89162
89037
89153
89004
89152
89132
89018
89033
89155
89105
89157
89161
89124
89179
89112
89140
89046
89126
89193
89410
89165
89116
89019
89150
89502
89036
89016
89195
89040
89039
89181
89125
89160
89173
89050
891118

In [60]:
for i in sf_zipcodes:
    if i not in ['CA','Ca']:
        if int(i) == 94901:
            print(i)

94901

In [61]:
import collections
counter=collections.Counter(postal_codes)

In [62]:
counter

Counter({'T2E 6L6': 1,
         '89002': 1,
         'H2G 1K7': 1,
         '85003': 1,
         'T2H 0N5': 1,
         '85024': 1,
         'M6G 1K8': 1,
         'L4T 1A8': 1,
         '85323': 1,
         '15213': 1,
         'L3R 1M5': 1,
         'M6G 2L7': 1,
         '85007': 1,
         'H2W 1Z3': 1,
         'T2K': 1,
         'T3C 1S2': 1,
         'H2Y 3B3': 1,
         '89106': 1,
         '89031': 1,
         '44115': 1,
         '85033': 1,
         'M6C 1B5': 1,
         '61856': 1,
         '85001': 1,
         'M5R 3K5': 1,
         'L5V 2X8': 1,
         '44241': 1,
         '53590': 1,
         '89128': 1,
         '85331': 1,
         '44062': 1,
         '44256': 1,
         '44112': 1,
         '85297': 1,
         '15241': 1,
         'L3R 1E9': 1,
         'M1M 1P8': 1,
         '89102': 1,
         'H1Z 2G1': 1,
         '85023': 1,
         'T2R 0S9': 1,
         '15202': 1,
         'M5S': 1,
         '89109': 1,
         'M3K 1E2': 1,
         'L3R 1E5': 1,
         '15146': 1,
         'L4K 2L7': 1,
         '28208': 1,
         '89131': 1,
         '28262': 1,
         '89149': 1,
         'T2W 4J3': 1,
         '85353': 1,
         '89141': 1,
         '85203': 1,
         '15236': 1,
         'M5S 1W2': 1,
         'T2E 1L8': 1,
         '89011': 1,
         '15232': 1,
         '44240': 1,
         '44118': 1,
         '85379': 1,
         '85296': 1,
         'M3A 1K8': 1,
         '85266': 1,
         'M5H 3V1': 1,
         '89146': 1,
         '85086': 1,
         '89130': 1,
         'L4L 0B2': 1,
         'M6G 3N2': 1,
         '28203': 1,
         '28277': 1,
         'L3T 1S9': 1,
         'L5B 2G6': 1,
         'T2T 1Z4': 1,
         'M8W 1N2': 1,
         'M5N 0A1': 1,
         'M4G 3C1': 1,
         '85282': 1,
         '85019': 1,
         '89012': 1,
         '28054': 1,
         '89030': 1,
         'T2H 0L8': 1,
         '28217': 1,
         '85253': 1,
         '85257': 1,
         '44135': 1,
         'M4P 1G6': 1,
         'M4E 1H5': 1,
         '44116': 1,
         '85305': 1,
         'M2N 7L3': 1,
         '85022': 1,
         'T2G 3N8': 1,
         'M5V 2B4': 1,
         '28227': 1,
         '89135': 1,
         'M9W 1J1': 1,
         'L4C 1V6': 1,
         'M5V 2A6': 1,
         'H2X 2T6': 1,
         '85258': 1,
         '85210': 1,
         'H2W 1M1': 1,
         '44128': 1,
         '85382': 1,
         'H2B 1X7': 1,
         '85034': 1,
         '89110': 1,
         '85204': 1,
         '44286': 1,
         '89169': 1,
         'M2N': 1,
         'H7T 1C8': 1,
         'M2N 7A1': 1,
         '44113': 1,
         '44130': 1,
         'M9V 4B4': 1,
         '89121': 1,
         'T2H 2W3': 1,
         '85202': 1,
         '44125': 1,
         '76829': 1,
         'M4H 1P6': 1,
         '89120': 1,
         'M6H 1A1': 1,
         '28212': 1,
         'H2L 1R3': 1,
         '89086': 1,
         '85338': 1,
         '85029': 1,
         'T3H 0V5': 1,
         '85012': 1,
         '28270': 1,
         '85027': 1,
         '28269': 1,
         '85031': 1,
         '44060': 1,
         '89118': 1,
         '44001': 1,
         'H3T 1Y1': 1,
         'M9W 0B5': 1,
         '28105': 1,
         '44022': 1,
         'H3B 4W8': 1,
         'H3G 2B2': 1,
         '85250': 1,
         '89148': 1,
         '85044': 1,
         'L5H 1G6': 1,
         '15201': 1,
         'M2N 5X2': 1,
         'T2W 3X6': 1,
         'L4Z 3M2': 1,
         'L1T 3A6': 1,
         'L4J 4P8': 1,
         '85339': 1,
         'H2Y 1G6': 1,
         'L5G 2T8': 1,
         '89119': 1,
         'T1Y 5E2': 1,
         'M8V 1A1': 1,
         '44107': 1,
         '85085': 1,
         'M5T 2K2': 1,
         'M1K 1M2': 1,
         '28205': 1,
         '53711': 1,
         'T2H 2S8': 1,
         '15222': 1,
         'T2X 1L3': 1,
         'L6L 1H2': 1,
         'M4J 1N2': 1,
         'L4A 1A2': 1,
         '53715': 1,
         '89113': 1,
         '85249': 1,
         'M3H 5R9': 1,
         '28206': 1,
         'M6H 1A5': 1,
         '28112': 1,
         '15203': 1,
         'H2X 3L7': 1,
         '85017': 1,
         '28215': 1,
         'L5M 4Z5': 1,
         '89117': 1,
         'M4K 1P1': 1,
         '89129': 1,
         '85281': 1,
         '85201': 1,
         'T2P 1G4': 1,
         '89123': 1,
         '44212': 1,
         'T2R 0G4': 1,
         'YO11 2AG': 1,
         '85268': 1,
         '53705': 1,
         'T2X 0G2': 1,
         'M3H 3M4': 1,
         '89183': 1,
         '89032': 1,
         'H2W 2C7': 1,
         'L3Y 4V8': 1,
         'M6H 1A4': 1,
         '89147': 1,
         'M5X 1A9': 1,
         '89122': 1,
         'L5H 4C7': 1,
         'H2Y 1J2': 1,
         'M6H 1N6': 1,
         '89134': 1,
         '85395': 1,
         'M5H 3P5': 1,
         'M5M 4A4': 1,
         '28120': 1,
         '85008': 1,
         '44129': 1,
         'L5A 4K3': 1,
         'T2A 2N9': 1,
         'M4Y': 1,
         'M5M 4A5': 1,
         'M8X 1C4': 1,
         'YO12': 1,
         'H2J 2J3': 1,
         'M5B 1J3': 1,
         '85283': 1,
         'M1H 1A9': 1,
         'J4H 1E7': 1,
         '29708': 1,
         '15218': 1,
         '85340': 1,
         'T2H 3C1': 1,
         'T3G 4P5': 1,
         '53593': 1,
         '15219': 1,
         'T3E 0B3': 1,
         'H4P 1V5': 1,
         '28173': 1,
         'L5E 1V4': 1,
         '53703': 1,
         '53719': 1,
         'T2E 7V8': 1,
         'H2X 3K7': 1,
         '44011': 1,
         '44124': 1,
         'H9S 4M2': 1,
         'M1K 4E7': 1,
         'H3X 1V6': 1,
         'L5N 8E8': 1,
         '53713': 1,
         '15220': 1,
         '28104': 1,
         '89044': 1,
         'M6G 1K3': 1,
         'M6G 1M4': 1,
         'L6H 4L2': 1,
         'L5M 5A2': 1,
         'L6V 1B9': 1,
         'T2Z': 1,
         '44145': 1,
         '53716': 1,
         '85032': 1,
         'H2Z 0A8': 1,
         'H4A 2A5': 1,
         '85378': 1,
         '85304': 1,
         '61820': 1,
         'M5S 3K6': 1,
         'M5V 3T4': 1,
         'L6A 1W2': 1,
         'M6J 2Z9': 1,
         'M4K 1N7': 1,
         '85284': 1,
         '85251': 1,
         '61822': 1,
         '15090': 1,
         '85381': 1,
         'M4Y 2X6': 1,
         'M1V': 1,
         '15237': 1,
         '85295': 1,
         '44146': 1,
         'M4M 1H3': 1,
         '85260': 1,
         '85225': 1,
         'M4C 1K5': 1,
         '85383': 1,
         'T2Z 4E7': 1,
         '44147': 1,
         '89104': 1,
         '85013': 1,
         '44224': 1,
         '61953': 1,
         '85224': 1,
         'H2L 1Z1': 1,
         '85308': 1,
         'L5B 0G4': 1,
         '15106': 1,
         '85286': 1,
         'L5G 1G1': 1,
         'H2S 1L9': 1,
         '85028': 1,
         'M6B 1W8': 1,
         'M1T 1V7': 1,
         'T3P 0C5': 1,
         'M2J 5A7': 1,
         'L3Y 8S4': 1,
         'L4K 5C3': 1,
         '44264': 1,
         '15217': 1,
         'L4W 5A8': 1,
         'H3H 2L8': 1,
         'L3R 0W4': 1,
         'M4N 2H9': 1,
         '89158': 1,
         'H7T 1C7': 1,
         'M5A 2M6': 1,
         'T2P 2B8': 1,
         '15227': 1,
         'L1S 3V4': 1,
         'T3G 2T3': 1,
         'H3B 1C8': 1,
         '85306': 1,
         'T2E 4Y7': 1,
         'T3R': 1,
         'M8W 1P4': 1,
         '85355': 1,
         'L6M 2R8': 1,
         '28032': 1,
         'H2X 3K8': 1,
         '15126': 1,
         'M4Y 2G1': 1,
         '85018': 1,
         '89052': 1,
         'L1V 1B8': 1,
         'H3G 2H7': 1,
         'M5V 2A5': 1,
         '28056': 1,
         '15224': 1,
         '85213': 1,
         'T3A 5H7': 1,
         'J7Y 4P7': 1,
         'T2H 2B8': 1,
         '53704': 1,
         'T2H': 1,
         'M4M 1Z7': 1,
         'M2P 2A8': 1,
         '85215': 1,
         '28211': 1,
         'M6A': 1,
         'M5R 1A8': 1,
         '85043': 1,
         '61801': 1,
         '85255': 1,
         'J0N 1E0': 1,
         'H3B 2V5': 1,
         '15632': 1,
         '15642': 1,
         'M3B 1Y6': 1,
         '85307': 1,
         'J7C 2J6': 1,
         '28204': 1,
         '53589': 1,
         '85236': 1,
         'H2H 1K4': 1,
         'L4C 3N8': 1,
         '15024': 1,
         'L5N 8P7': 1,
         'L4K 1R9': 1,
         'M5B 2H6': 1,
         '28134': 1,
         'L3P 1X3': 1,
         '15108': 1,
         '44139': 1,
         '85051': 1,
         'M4X 1K2': 1,
         '89014': 1,
         'T2E 6W5': 1,
         'H9R 5A5': 1,
         'L3T 4X1': 1,
         '89101': 1,
         '28052': 1,
         'M4W 3E2': 1,
         'M1S 4N3': 1,
         'M3C 1V6': 1,
         'T2H 2L9': 1,
         '15212': 1,
         '85014': 1,
         '85004': 1,
         '15206': 1,
         'M6K 1V2': 1,
         'L4W 0B8': 1,
         'M5R 2E3': 1,
         'L4K 5P1': 1,
         'J4Y 1V9': 1,
         '28078': 1,
         'M1S 5B8': 1,
         'M5V 2G3': 1,
         '89103': 1,
         'M6E 1C5': 1,
         'H4C 1P4': 1,
         'T3A 0E2': 1,
         '28210': 1,
         'J3E 2T4': 1,
         'T2G 5C3': 1,
         'L5C 1C6': 1,
         'M5T 1R9': 1,
         'L4B 3P4': 1,
         '85212': 1,
         '44114': 1,
         'H1Y 1L7': 1,
         'M6E 1A1': 1,
         '85248': 1,
         'L4H 2Z7': 1,
         'M3C 3R6': 1,
         'H2R 1G5': 1,
         'H3A 1J7': 1,
         'H3N 1W9': 1,
         '15209': 1,
         '28012': 1,
         'M4P 2C6': 1,
         'L4W 3Z3': 1,
         'H4N 1K5': 1,
         '44333': 1,
         '44123': 1,
         'T3A 3S8': 1,
         'M1R 2Z4': 1,
         'L4H 0J2': 1,
         'L4W 1S9': 1,
         '15120': 1,
         '88901': 1,
         'M6G 1L8': 1,
         'M5T 2K1': 1,
         'M4T 1L9': 1,
         'H1Y 1X6': 1,
         'H3G 2E8': 1,
         'M5R 1A6': 1,
         'M1W': 1,
         'L4B 3Z4': 1,
         'L3R 1K9': 1,
         '85226': 1,
         '44056': 1,
         '61821': 1,
         'M6A 2T9': 1,
         'M5S 1X6': 1,
         'H2L 4G3': 1,
         'T2T 4Z6': 1,
         'M6A 3B2': 1,
         '85206': 1,
         '15229': 1,
         '85016': 1,
         '44121': 1,
         '44122': 1,
         '15205': 1,
         'M4Y 2C8': 1,
         'M9C 1B8': 1,
         'M3C 0G6': 1,
         '53718': 1,
         'H7K 2K2': 1,
         'T2L 2A6': 1,
         'H2L 2H8': 1,
         'M5B 1Y7': 1,
         '85207': 1,
         '85143': 1,
         'H8N 1T7': 1,
         'L0G 1N0': 1,
         '44077': 1,
         'M7A': 1,
         'M1S 3P6': 1,
         'M6E 1B5': 1,
         'M1W 3E2': 1,
         'T3B 1B9': 1,
         '89138': 1,
         '85302': 1,
         'M1P 2S8': 1,
         '15101': 1,
         'M4L 1C4': 1,
         'H7T 2W5': 1,
         'L6V 1B1': 1,
         'T2E 9A7': 1,
         '15226': 1,
         '15317': 1,
         'M5S 1Y3': 1,
         '44026': 1,
         '44103': 1,
         'T2J 7G9': 1,
         'H2G 2M8': 1,
         'L6H 7G9': 1,
         'L4L 1A6': 1,
         '85234': 1,
         'H4A 1W4': 1,
         '44120': 1,
         'M6J 1V9': 1,
         '85256': 1,
         'M5G 0A1': 1,
         'M1L 2L9': 1,
         '44087': 1,
         'T2W 1E8': 1,
         '44149': 1,
         '44094': 1,
         '85246': 1,
         'M5J 2M4': 1,
         'L3P 8M1': 1,
         'L5B 2C9': 1,
         'M5V 2G4': 1,
         'L4G 1L8': 1,
         '15017': 1,
         '85048': 1,
         '85233': 1,
         'M4W 2H1': 1,
         'L5T 1A6': 1,
         '85042': 1,
         '85303': 1,
         'M8Z 1M8': 1,
         '44221': 1,
         'M4Y 2C6': 1,
         'M1B 2W4': 1,
         'L4L 8B7': 1,
         '44067': 1,
         '85259': 1,
         'L1V 6Y9': 1,
         'M4W 1S9': 1,
         '53575': 1,
         '85009': 1,
         '28031': 1,
         'M5G 1C7': 1,
         'L4X 3S1': 1,
         'T2G 0A3': 1,
         'M5T': 1,
         '28214': 1,
         'L7E 2B1': 1,
         '28209': 1,
         '28216': 1,
         'L6E 2C9': 1,
         'T2E 6Z3': 1,
         'L5N 3M4': 1,
         'M8V 1C5': 1,
         'M1B 5M5': 1,
         'M5P 3L3': 1,
         '44039': 1,
         '89107': 1,
         'L6A 2W2': 1,
         'L3T 0C7': 1,
         'J4Z 3H1': 1,
         '89074': 1,
         'L4B 1G2': 1,
         'L4K 5Y6': 1,
         'M4R 2H1': 1,
         '89139': 1,
         '29715': 1,
         'M5T 1H1': 1,
         'M5B 2L7': 1,
         'M5T 1S9': 1,
         'H2X 3V4': 1,
         '28164': 1,
         'M5A 4K9': 1,
         'T2C 2B4': 1,
         'L6T 5N9': 1,
         '44134': 1,
         'M5T 2G6': 1,
         'M8Z 1S5': 1,
         'M1S 1V2': 1,
         'L4K 0A4': 1,
         '15144': 1,
         '44143': 1,
         '44126': 1,
         'L1V 1X6': 1,
         '15238': 1,
         'M1S 4T5': 1,
         'M4K 3V5': 1,
         'H1V 1A1': 1,
         'T2T 5H8': 1,
         'T2S 1W3': 1,
         'H4R 3C8': 1,
         '85037': 1,
         'T2E 2T4': 1,
         'M5H 3M9': 1,
         'T1Y 6J7': 1,
         '85301': 1,
         'M4W 1L4': 1,
         '15137': 1,
         'M6R 1A4': 1,
         'M4C 1H6': 1,
         'L4C 1V4': 1,
         '89108': 1,
         'L6V 1B2': 1,
         'M1V 1V3': 1,
         'M4S 2M5': 1,
         'L6W 2B3': 1,
         '15147': 1,
         'M6P 3L4': 1,
         'L4H 5Y3': 1,
         '85020': 1,
         'M1P': 1,
         'L3T 1L3': 1,
         '28202': 1,
         'M3A 1Z5': 1,
         'T2H 0G9': 1,
         '15122': 1,
         '85388': 1,
         'H3G 2X1': 1,
         'M6B 1R7': 1,
         'L5M 6J3': 1,
         'H3B 1P4': 1,
         '85363': 1,
         'L6J 1J6': 1,
         'T2S 1W9': 1,
         'H3A': 1,
         'H3A 2K3': 1,
         'L4K 5W4': 1,
         'T2S 1W7': 1,
         'L4K 3B9': 1,
         '85392': 1,
         'M1V 5P6': 1,
         'M5M 4A6': 1,
         'L4W 4G1': 1,
         'L6C 1P8': 1,
         'T2C 4T8': 1,
         'M4J 2T8': 1,
         'M5V 2R3': 1,
         'M4M 1H4': 1,
         'L5R 3V2': 1,
         'H4C': 1,
         'M4M 2G1': 1,
         'T3E 4N3': 1,
         'M5T 2M2': 1,
         '44278': 1,
         'H3T 1M2': 1,
         'H2Z 1P3': 1,
         '85351': 1,
         '85310': 1,
         'M6E 1B7': 1,
         'M1V 1V2': 1,
         '44178': 1,
         'M6H 4A9': 1,
         '15235': 1,
         'M5V 1Z4': 1,
         'J5R 0A1': 1,
         'YO22 4DE': 1,
         'T2B 2Z1': 1,
         'H3J 1M3': 1,
         '53532': 1,
         'H2L 3T1': 1,
         'L4J 1V8': 1,
         '89142': 1,
         'H9B 1P7': 1,
         'H3T 1Y5': 1,
         'L4H 0S5': 1,
         '85080': 1,
         'L3T 7Y9': 1,
         'T2P 0S4': 1,
         'M5G 1M5': 1,
         '29707': 1,
         'T2E 2P2': 1,
         'T1Y 6Y7': 1,
         'M2R 2A5': 1,
         'J0R 1R6': 1,
         'M9L 2K9': 1,
         'M5T 2M1': 1,
         'H2X 2X7': 1,
         'M5J 2G4': 1,
         'L4J': 1,
         'M4K 2S1': 1,
         'M3M 3G5': 1,
         'M1W 2S8': 1,
         'M5S 1Y6': 1,
         'M4E 1G8': 1,
         '89178': 1,
         'M1B 0C2': 1,
         'M5B 2H1': 1,
         'L4J 8L7': 1,
         'M4W 1J6': 1,
         'H2S 1A1': 1,
         'J7A 2H3': 1,
         'M4P 2E6': 1,
         '15140': 1,
         'L6H 6C8': 1,
         'M4Y 2B7': 1,
         'M4P 3B7': 1,
         '15148': 1,
         'M1S': 1,
         'M6S 1R7': 1,
         'H1N 1C7': 1,
         'H2S 3S3': 1,
         'T2Y 4H3': 1,
         'M6K 3P6': 1,
         'M4C 1L4': 1,
         'L5C 1T8': 1,
         '85053': 1,
         'L4W 4K2': 1,
         'M3H 6A8': 1,
         'T2M 2A8': 1,
         'M6A 2T2': 1,
         'M6J': 1,
         'M5V 3J3': 1,
         'M7A 2C7': 1,
         '15026': 1,
         'M1V 5G9': 1,
         'M5S 2X9': 1,
         '44111': 1,
         'H2X 2V5': 1,
         'H2L 4M4': 1,
         'M6S 1P2': 1,
         'H4A 1Y1': 1,
         'M5H 1J8': 1,
         'J7G 1A9': 1,
         'M4S 1S5': 1,
         'M4M 1H1': 1,
         'M4C 1K1': 1,
         'T2V 1H2': 1,
         'M6S 1N6': 1,
         '15221': 1,
         'M5T 2G3': 1,
         '85208': 1,
         'M4N': 1,
         'M6M 1B9': 1,
         'T3G 3T2': 1,
         'L3T 2C4': 1,
         '44070': 1,
         '44109': 1,
         'M5T 2G7': 1,
         'J7Y 4Y2': 1,
         'M2K 2X9': 1,
         'T2W 1G8': 1,
         'L5G 1G7': 1,
         'M5V': 1,
         'M4Y 1Y5': 1,
         'L4L 9C8': 1,
         'M3B 1X8': 1,
         'M4E 1E9': 1,
         '85046': 1,
         'M5E 1C4': 1,
         'M6J 1E5': 1,
         '85545': 1,
         'M6C 2C7': 1,
         'M6J 2Z7': 1,
         '44236': 1,
         'T2C 1J3': 1,
         'M6C 1B2': 1,
         '85326': 1,
         '15668': 1,
         'L6W 3E7': 1,
         'H2Z 1B9': 1,
         'T3P 0A3': 1,
         'H3A 0G4': 1,
         'M1B 2G5': 1,
         'M2N 3K5': 1,
         'M1S 2C1': 1,
         'H3H 2V5': 1,
         '85006': 1,
         'H4C 1S7': 1,
         '28213': 1,
         'M4G 3T8': 1,
         '85205': 1,
         'H3Z 2M8': 1,
         'M4M 2T4': 1,
         'J3Y 4J6': 1,
         'L1V 1W9': 1,
         'T1Y 5T4': 1,
         'M6S 3Z6': 1,
         'M5C 3H5': 1,
         'M4Y 2J9': 1,
         'M5T 1R5': 1,
         'H3J 1N6': 1,
         'J4Y 1A4': 1,
         'H2G 2Z6': 1,
         'H9X 1M2': 1,
         'M4Y 1Z3': 1,
         'M5M 3X3': 1,
         'M4C 1H8': 1,
         'T2E 2Y7': 1,
         'L4K 0H1': 1,
         'J4V 2J2': 1,
         'T2V 5A8': 1,
         'M1P 2K5': 1,
         'M4J 1L2': 1,
         'H2X 2H6': 1,
         'T3C 3N6': 1,
         'L4L 9K8': 1,
         'H2V 1J8': 1,
         'L5M 1L9': 1,
         '44017': 1,
         'T3E 0A8': 1,
         'T2J 0B2': 1,
         'H2T 1A8': 1,
         'M2K 1C2': 1,
         'M8V 1J1': 1,
         'M4S 2M2': 1,
         'M6R 1X7': 1,
         'J7E 3H3': 1,
         '': 1,
         '53597': 1,
         'H7G 2W2': 1,
         'J7A 2H2': 1,
         'H4X 1Z2': 1,
         '44024': 1,
         'H2L 4S9': 1,
         '92328': 1,
         '44144': 1,
         '61802': 1,
         'L5T 2X6': 1,
         'M1G 1P6': 1,
         'M6A 3A1': 1,
         'H2V 1W2': 1,
         'M5V 2B7': 1,
         'M6P 3T1': 1,
         'M2N 5R6': 1,
         'M8Z 1V1': 1,
         'M5E 1R2': 1,
         'M9V 5E2': 1,
         'M5H 3M7': 1,
         'T2T 3V2': 1,
         '1636': 1,
         'J7N 0A6': 1,
         'T3E 0A2': 1,
         'M6S 1N3': 1,
         'H1Y 3L1': 1,
         'L4C 3E3': 1,
         'M4N 2L9': 1,
         'L4T 1A6': 1,
         'L3Y 8X7': 1,
         'M6K 1V4': 1,
         '44110': 1,
         'T2P 0T9': 1,
         'L4C 8S7': 1,
         '28025': 1,
         'L3R 8R7': 1,
         '85041': 1,
         'H3V 1G6': 1,
         'M4Y 2C9': 1,
         'L3Y 8C9': 1,
         'T2R 1M7': 1,
         'L5V 2R4': 1,
         'M4E 1E3': 1,
         'M4K 1N2': 1,
         'M5B 1E4': 1,
         'H3H 2H9': 1,
         'H2T 2N9': 1,
         'M4J 3S2': 1,
         'L4B': 1,
         '93462': 1,
         'J6J 4J5': 1,
         'M6K 1L7': 1,
         'M5H 4G3': 1,
         'M6E 2G7': 1,
         'M6G 1C2': 1,
         'L3R 9V7': 1,
         'M4C 1K4': 1,
         'T2G 0Y7': 1,
         'M5V 2B6': 1,
         'H2Y 2A6': 1,
         'L5M': 1,
         'M5M 3Z5': 1,
         '15216': 1,
         'M4R 2H6': 1,
         'L4B 3B4': 1,
         'T2H 0N7': 1,
         'L4B 3H7': 1,
         'T2E 3J6': 1,
         'T2P 4L4': 1,
         'M3J 2T2': 1,
         '28034': 1,
         'M1B 3A4': 1,
         'T3G 2Z3': 1,
         'M5B': 1,
         'T2T 3V8': 1,
         'M4L 1H3': 1,
         'T2J 7A4': 1,
         'M4Y 1V8': 1,
         'M1P 2G7': 1,
         'M4W 2L8': 1,
         'M8Z 4Y1': 1,
         'T2P 1B8': 1,
         'M5T 1P7': 1,
         '85312': 1,
         'WA15 9SN': 1,
         'M5L 2L4': 1,
         'M6S 1N8': 1,
         'M2N 3G1': 1,
         'H4J 1C4': 1,
         'M4S 2A3': 1,
         'H2T 1R9': 1,
         'M8W 1P5': 1,
         'T1Y': 1,
         'T3H 1E9': 1,
         'L5N 6B9': 1,
         'M5G 2L2': 1,
         'M4Y 1E3': 1,
         'M8X 1C7': 1,
         'M5G 2K4': 1,
         'M4T 1K2': 1,
         'H3B 4R7': 1,
         'M6K 3C5': 1,
         'L4Y 2N4': 1,
         '15015': 1,
         'T2X 3W5': 1,
         'M4W 2J1': 1,

In [3]:
vegas_df = pd.read_csv('vegas_data.csv')

In [77]:
vegas_df.describe(include='all').transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Serial Number,166490,166490,DA0886670,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Permit Number,166490,21933,PR0020660,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Restaurant Name,166487,22122,Roberto's Taco Shop,610,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location Name,166480,10744,CAESARS PALACE HOTEL & CASINO,1617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category Name,166490,30,Restaurant,69917,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Address,166427,9293,3799 S Las Vegas Blvd,1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,166472,35,Las Vegas,133588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,166490,1,Nevada,166490,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip,166471,3551,89109,6510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Current Demerits,166490,NaN,NaN,NaN,3.90979,4.23313,0,0,3,6,100
Current Grade,166462,6,A,164135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date Current,166490,2358,03/15/2017 12:00:00 AM,1249,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inspection Date,166490,2947,01/25/2016 12:00:00 AM,189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inspection Time,166441,114704,01/01/1900 12:00:00 AM,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Employee ID,166490,205,EE7000327,4473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inspection Type,166490,4,Routine Inspection,150095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inspection Demerits,166490,NaN,NaN,NaN,5.75941,6.55513,0,0,4,8,250
Inspection Grade,164790,10,A,143504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Permit Status,39645,7,A,33736,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inspection Result,166490,25,Compliant,104783,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Violations,127621,36587,2930,4232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Record Updated,166490,109112,02/21/2013 10:26:12 PM,53368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location 1,166490,9367,"(36.1022507, 115.1699679)",1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
lv_zip = [89044, 89054, 89101, 89102, 89103, 89104, 89106, 89107,
          89108, 89109, 89110, 89113, 89115, 89117, 89118, 89119, 89120, 
          89121, 89122, 89123, 89124, 89128, 89129, 89130, 89131, 89134, 
          89135, 89138, 89139, 89141, 89142, 89143, 89144, 89145, 89146, 89147, 
          89148, 89149, 89156, 89158, 89161, 89165, 89166, 89169, 89178, 89179, 89183, 89199]
lv_zip = [str(i) for i in lv_zip]

In [5]:
vegas_yelp_df= df[df['postal_code'].isin(lv_zip)]

In [6]:
vegas_main_df = vegas_df.replace(regex = r'(?<=\d{5})-\d+', value = '')

In [7]:
vegas_yelp_df=vegas_yelp_df.rename(columns={'Address':'address','postal_code':'zip'})
vegas_main_df=vegas_main_df.rename(columns={'Address':'address','Zip':'zip'})

In [8]:
print(vegas_main_df.zip.describe())
print(vegas_yelp_df.zip.describe())

count     166471
unique       132
top        89109
freq       33702
Name: zip, dtype: object
count     28520
unique       48
top       89109
freq       3130
Name: zip, dtype: object

In [9]:
merged_df=vegas_yelp_df.merge(vegas_main_df,on=['address'],how='inner')

In [13]:
len(merged_df)

764851

In [15]:
merged_df.columns

Index(['address', 'attributes', 'attributes.AcceptsInsurance',
       'attributes.AgesAllowed', 'attributes.Alcohol', 'attributes.Ambience',
       'attributes.BYOB', 'attributes.BYOBCorkage', 'attributes.BestNights',
       'attributes.BikeParking', 'attributes.BusinessAcceptsBitcoin',
       'attributes.BusinessAcceptsCreditCards', 'attributes.BusinessParking',
       'attributes.ByAppointmentOnly', 'attributes.Caters',
       'attributes.CoatCheck', 'attributes.Corkage',
       'attributes.DietaryRestrictions', 'attributes.DogsAllowed',
       'attributes.DriveThru', 'attributes.GoodForDancing',
       'attributes.GoodForKids', 'attributes.GoodForMeal',
       'attributes.HairSpecializesIn', 'attributes.HappyHour',
       'attributes.HasTV', 'attributes.Music', 'attributes.NoiseLevel',
       'attributes.Open24Hours', 'attributes.OutdoorSeating',
       'attributes.RestaurantsAttire', 'attributes.RestaurantsCounterService',
       'attributes.RestaurantsDelivery', 'attributes.RestaurantsGoodForGroups',
       'attributes.RestaurantsPriceRange2',
       'attributes.RestaurantsReservations',
       'attributes.RestaurantsTableService', 'attributes.RestaurantsTakeOut',
       'attributes.Smoking', 'attributes.WheelchairAccessible',
       'attributes.WiFi', 'business_id', 'categories', 'city', 'hours',
       'hours.Friday', 'hours.Monday', 'hours.Saturday', 'hours.Sunday',
       'hours.Thursday', 'hours.Tuesday', 'hours.Wednesday', 'is_open',
       'latitude', 'longitude', 'name', 'neighborhood', 'zip_x',
       'review_count', 'stars', 'state', 'Serial Number', 'Permit Number',
       'Restaurant Name', 'Location Name', 'Category Name', 'City', 'State',
       'zip_y', 'Current Demerits', 'Current Grade', 'Date Current',
       'Inspection Date', 'Inspection Time', 'Employee ID', 'Inspection Type',
       'Inspection Demerits', 'Inspection Grade', 'Permit Status',
       'Inspection Result', 'Violations', 'Record Updated', 'Location 1'],
      dtype='object')

In [19]:
temp_df=merged_df[merged_df['name']==merged_df['Restaurant Name']]
len(temp_df)
len(temp_df.name.unique())

201

In [20]:
temp_df.name.unique()

array(['Omelet House Summerlin', "Mimi's Cafe", 'Subway',
       'Paradise Boba Tea and Smoothie', "Samurai Sam's",
       "Frank & Fina's Cocina", "Angelina's Pizzeria",
       'The Teriyaki Company', 'Panda Express', "Emjay's New York Pizza",
       'Slices Pizzeria', 'Hunan Jiu Jia', "McDonald's",
       "Long John Silver's", "BJ'S Cocktail Lounge South",
       'Rocky Mountain Chocolate Factory', 'Courtyard Cafe',
       'Thai Cuisine', "Harold's Chicken & Fish", 'Sushi Yamaguchi',
       "Binion's Cafe", "Capriotti's Sandwich Shop",
       "Romano's Macaroni Grill", "Roberto's Taco Shop", 'Panera Bread',
       'Baja Fresh', "Dee's Donuts", 'Tropical Smoothie Cafe',
       'Double Yoke', 'Town Center Lounge', 'El Buen Gusto',
       'Four Sevens Sports Bar & Restaurant', 'Blue Diamond Saloon',
       "Sicily's Pizza", 'New China Buffet', 'The Las Vegas Grille',
       'Pho Saigon 8', 'Salcianu Bistro',
       'Orchids Garden Chinese Restaurant', 'Gyro Time',
       'Taqueria Santander', 'Cellar Lounge', "Mega Tom's Burgers",
       'Shalimar Restaurant', 'Yayo Taco', 'Dairy Queen',
       'Thai Style Noodle House', "Sugar's", 'Aloha Island Grill',
       'Tacos El Compita', 'Four Mile Bar', 'Northern China Restaurant',
       'Aloha Kitchen', 'Crown Bakery', 'Yogurtland',
       "Fuzziwig's Candy Factory", "Jason's Deli", "Lefty's Pizza",
       'Manhattan Pizza II', 'Casa Di Amore', 'Starbucks',
       'Porchlight Grille', 'Molcasalsa Mexican Food', 'Chow King',
       'Red Ribbon Bakeshop', 'Farmer Boys', 'San Salvador Restaurant',
       'Crab Corner', 'Little Caesars Pizza', "Jack's Place",
       'Big Wong Restaurant', 'Pasta Mia West',
       'Baja California Restaurant & Cantina', 'Rincon Catracho',
       "Dunkin' Donuts", "Bambino's East Coast Pizzeria",
       'Market Grille Cafe', 'China Pantry', 'Italia Express',
       'Bangkok 9', 'Taco Time', 'Tofu Hut', 'Los Tacos', "Cici's Pizza",
       'Yogis Teriyaki House', 'Chicago Tasty Dogs', 'Yoshinoya',
       "Jake's Bar", 'Mt Charleston Lodge Restaurant', 'Espresso',
       'Chile Verde Express Mexican Grill', 'El Sombrero Cafe',
       "Olivia's Dollhouse Tea Room", "Annie's Kitchen",
       'Las Vegas Country Saloon', 'Cake World Bakery',
       'Torrey Pines Pub', 'Bonanza Lounge', 'Bonito Michoacan',
       'Crowbar', 'Fatburger', 'Qdoba Mexican Grill',
       'La Playita Restaurant', "Anna's Garden", 'Brown Bag Lunches',
       "Chaser's Pub", 'Round Table Pizza', "Archi's Thai Cafe",
       'Pura Vida Bakery & Bystro', 'Donut Tyme', 'Sedona Lounge',
       "Bentley's Coffee", 'Las Americas', 'La Takiza',
       "Church's Chicken", "Jimmy John's Gourmet Sandwiches",
       'Club Car Lounge', 'Hawaiian Hale', 'Los Molcajetes',
       'Mandarin Express', "Felipito's Mexican Food", 'Tacos El Rodeo',
       'Indian Curry Bowl', 'Barcelona Tapas', "Wendy's Noodle Cafe",
       'IHOP', 'Pho 87', 'Prommares Thai Food', 'Arandas Taqueria',
       'Pizza Patron', 'Tacos El Gordo', 'Beauty Bar',
       "Cugino's Pizzeria", 'Brothers Italian Bistro', "Joe's Crab Shack",
       'Farm Basket', 'Mariscos Vallarta', 'Che Inka Chicken',
       "Michael's Pub", 'Greek American Grille',
       'Maru Korean BBQ & Sushi', 'Hawaiian Style Poke',
       'Diamond Cabaret', 'Macayo Vegas', 'Top This Pizza',
       'Port of Subs', 'Chinatown Cuisine', 'Tortas El Rey',
       'China Star Buffet', 'Luna Rossa', 'Salvadoreno Restaurant',
       'Star Mexican Grill', 'Lake Mead Tavern', "Brooklyn Billy's",
       'Diamond Chinese Restaurant', "Roy's Restaurant",
       'Atlanta Bread Company', "Uncle Joe's Pizza",
       "Carrabba's Italian Grill", 'Manhattan Pizza IV', 'El Cordobes',
       'Sorrento Pizza', 'Del Taco', "Lucky's Lounge",
       'Sunrise Too Donuts', 'Sunshine Cafe', 'Sweet Tomatoes',
       'German Bread Bakery', 'Hoops Food & Spirits',
       'Peppers Mexican Grill', 'Five Star Tavern', "Buck's Tavern",
       "Marco's Pizza", 'Pizza Company', 'Ramen Sora', 'Woo Che',
       'Odyssey Pizza', 'Lakes Lounge', 'Outback Steakhouse', 'China One',
       'Sushi Twister', 'Thai Taste', 'Krazy Buffet', 'El Steak Burrito',
       'Chopstix Express', 'Krung Thai Restaurant', "Chubby's Pub",
       'Palm Pizza', 'Pastry Palace', 'Godiva Chocolatier',
       'Stadium Saloon', 'Vanguard Lounge', 'Red Shrimp Company',
       'Speed Zone Tavern', "Chang's Hong Kong Cuisine", 'Gourmet Wok',
       "Northside Nathan's", 'Chipotle Mexican Grill', "Lee's Sandwiches",
       "Kathy's Southern Cooking", 'Black Bear Diner'], dtype=object)

In [ ]:
data_add = vegas_df.Address.unique()

In [110]:
yelp_add = vegas_main_df.address.unique()

In [108]:
from fuzzywuzzy import fuzz

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [109]:
count = 0 

fuzz.token_sort_ratio('shreyas','shreyassss')

82

In [118]:
count=0
for i in data_add:
    for j in yelp_add:
        if fuzz.token_sort_ratio(i,j)>97:
            print(i,j)
            count+=1

3355 S Las Vegas Blvd 3355 S Las Vegas Blvd
3355 S Las Vegas Blvd 3355 Las Vegas Blvd S
5576 Boulder Hwy 5576 Boulder Hwy
2025 E SAHARA Ave 2025 E Sahara Ave
2025 E SAHARA Ave 2025 E Sahara ave
8590 W Cheyenne Ave 8590 W Cheyenne Ave
3555 S Las Vegas Blvd 3555 S Las Vegas Blvd
3555 S Las Vegas Blvd 3555 Las Vegas Blvd S
129 E Fremont St 129 E Fremont St
2601 S Eastern Ave 2601 S Eastern Ave
1950 N Rainbow Blvd 1950 N Rainbow Blvd
6441 N Durango Dr 6441 N Durango Dr
3708 S Las Vegas Blvd 3708 Las Vegas Blvd S
3708 S Las Vegas Blvd 3708 S Las Vegas Blvd
2535 S LAS VEGAS Blvd 2535 Las Vegas Blvd S
2535 S LAS VEGAS Blvd 2535 S Las Vegas Blvd
2535 S LAS VEGAS Blvd 2535 S. Las Vegas Blvd
10670 SOUTHERN HIGHLANDS Pkwy 10670 Southern Highlands Pkwy
3121 S Las Vegas Blvd 3121 Las Vegas Blvd S
2565 E Tropicana Ave 2565 E Tropicana Ave
4343 N Rancho Dr 4343 N Rancho Dr
3570 S Las Vegas Blvd 3570 Las Vegas Blvd S
3570 S Las Vegas Blvd 3570 S Las Vegas Blvd
4151 S Eastern Ave 4151 S Eastern Ave
347 N Nellis Blvd 347 N Nellis Blvd
4100 S Paradise Rd 4100 S Paradise Rd
2400 N Rancho Dr 2400 N Rancho Dr
2421 W Bonanza Rd 2421 W Bonanza Rd
3655 S DURANGO Dr 3655 S Durango Dr
640 N EASTERN Ave 640 N Eastern Ave
2245 E FLAMINGO Rd 2245 E Flamingo Rd
1 S Main St 1 S Main St
3900 S Las Vegas Blvd 3900 Las Vegas Blvd S
3900 S Las Vegas Blvd 3900 S Las Vegas Blvd
3900 S Las Vegas Blvd 900 S Las Vegas Blvd
5959 S Hualapai Way 5959 S Hualapai Way
7150 W Lake Mead Blvd 7150 W Lake Mead Blvd
3400 S Las Vegas Blvd 3400 Las Vegas Blvd S
3400 S Las Vegas Blvd 3400 S Las Vegas Blvd
439 Rock Quarry Way 439 Rock Quarry Way
3220 S DURANGO Dr 3220 S Durango Dr
1991 N Decatur Blvd 1991 N Decatur Blvd
3377 S Las Vegas Blvd 3377 Las Vegas Blvd S
3377 S Las Vegas Blvd 3377 So Las Vegas Blvd
3377 S Las Vegas Blvd 3377 S Las Vegas Blvd
221 N Rampart Blvd 221 N Rampart Blvd
3325 S Las Vegas Blvd 3325 Las Vegas Blvd S
3325 S Las Vegas Blvd 3325 S Las Vegas Blvd
3325 S Las Vegas Blvd 3325 Las Vegas Blvd. S
1 S MAIN St 1 S Main St
4401 N Rainbow Blvd 4401 N Rainbow Blvd
12 E Ogden Ave 12 E Ogden Ave
2411 W Sahara Ave 2411 W Sahara Ave
3460 S Hualapai Way 3460 S Hualapai Way
1089 E Tropicana Ave 1089 E Tropicana Ave
3081 N Rainbow Blvd 3081 N Rainbow Blvd
3790 S Las Vegas Blvd 3790 Las Vegas Blvd S
3790 S Las Vegas Blvd 3790 S Las Vegas Blvd
3535 S LAS VEGAS Blvd 3535 S Las Vegas Blvd
3535 S LAS VEGAS Blvd 3535 Las Vegas Blvd S
740 S Decatur Blvd 740 S Decatur Blvd
3477 S Durango Dr 3477 S Durango Dr
3085 N Rainbow Blvd 3085 N Rainbow Blvd
1821 N Las Vegas Blvd 821 Las Vegas Blvd N
11011 W Charleston Blvd 11011 W Charleston Blvd
3300 S LAS VEGAS Blvd 3300 Las Vegas Blvd S
3300 S LAS VEGAS Blvd 3300 S Las Vegas Blvd
2001 N Rainbow Blvd 2001 N Rainbow Blvd
124 S 11TH St 124 S 11th St
3340 S Highland Dr 3340 S Highland Dr
523 Fremont St 523 Fremont St
4500 W Tropicana Ave 4500 W Tropicana Ave
4111 Boulder Hwy 4111 Boulder Hwy
3700 W Flamingo Rd 3700 W Flamingo Rd
6770 N Durango Dr 6770 N Durango Dr
439 ROCK QUARRY Way 439 Rock Quarry Way
3300 S Las Vegas Blvd 3300 Las Vegas Blvd S
3300 S Las Vegas Blvd 3300 S Las Vegas Blvd
1940 Rock Springs Dr 1940 Rock Springs Dr
3950 N Tenaya Way 3950 N Tenaya Way
2201 S Fort Apache Rd 2201 S Fort Apache Rd
3960 S Las Vegas Blvd 3960 Las Vegas Blvd S
3960 S Las Vegas Blvd 3960 S Las Vegas Blvd
255 E Flamingo Rd 255 E Flamingo Rd
12300 S Las Vegas Blvd 12300 Las Vegas Blvd S
12300 S Las Vegas Blvd 12300 Las Vegas Blvd. S
12300 S Las Vegas Blvd 12300 S Las Vegas Blvd
2595 S Maryland Pkwy 2595 S Maryland Pkwy
6075 Spring Mountain Rd 6075 Spring Mountain Rd
3600 S Las Vegas Blvd 3600 S Las Vegas Blvd
3600 S Las Vegas Blvd 3600 Las Vegas Blvd S
4949 N Rancho Dr 4949 N Rancho Dr
4930 W Flamingo Rd 4930 W Flamingo Rd
4416 N Rancho Dr 4416 N Rancho Dr
855 S Grand Central Pkwy 855 S Grand Central Pkwy
855 S Grand Central Pkwy 855 S Grand Central Prkwy
3730 S Las Vegas Blvd 3730 Las Vegas Blvd S
3730 S Las Vegas Blvd 3730 S Las Vegas Blvd
5111 Boulder Hwy 5111 Boulder Hwy
3325 S LAS VEGAS Blvd 3325 Las Vegas Blvd S
3325 S LAS VEGAS Blvd 3325 S Las Vegas Blvd
3325 S LAS VEGAS Blvd 3325 Las Vegas Blvd. S
3151 E Washington Ave 3151 E Washington Ave

KeyboardInterrupt: